"""Add demographics

Revision ID: 2a013d1fc882
Revises: 77726879cce3
Create Date: 2026-03-28 19:20:08.081384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a013d1fc882'
down_revision: Union[str, Sequence[str], None] = '77726879cce3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_demographics',
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('total_enrollment', sa.Integer(), nullable=True),
    sa.Column('pct_men', sa.Float(), nullable=True),
    sa.Column('pct_women', sa.Float(), nullable=True),
    sa.Column('pct_white', sa.Float(), nullable=True),
    sa.Column('pct_black', sa.Float(), nullable=True),
    sa.Column('pct_hispanic', sa.Float(), nullable=True),
    sa.Column('pct_asian', sa.Float(), nullable=True),
    sa.Column('pct_native', sa.Float(), nullable=True),
    sa.Column('pct_pacific', sa.Float(), nullable=True),
    sa.Column('pct_two_or_more', sa.Float(), nullable=True),
    sa.Column('pct_unknown', sa.Float(), nullable=True),
    sa.Column('pct_non_resident', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organization.org_id'], ),
    sa.PrimaryKeyConstraint('org_id')
    )
    op.create_table('program_demographics',
    sa.Column('program_id', sa.String(length=36), nullable=False),
    sa.Column('total_completions', sa.Integer(), nullable=True),
    sa.Column('pct_men', sa.Float(), nullable=True),
    sa.Column('pct_women', sa.Float(), nullable=True),
    sa.Column('pct_white', sa.Float(), nullable=True),
    sa.Column('pct_black', sa.Float(), nullable=True),
    sa.Column('pct_hispanic', sa.Float(), nullable=True),
    sa.Column('pct_asian', sa.Float(), nullable=True),
    sa.Column('pct_native', sa.Float(), nullable=True),
    sa.Column('pct_pacific', sa.Float(), nullable=True),
    sa.Column('pct_two_or_more', sa.Float(), nullable=True),
    sa.Column('pct_unknown', sa.Float(), nullable=True),
    sa.Column('pct_non_resident', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['program.program_id'], ),
    sa.PrimaryKeyConstraint('program_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('program_demographics')
    op.drop_table('organization_demographics')
    # ### end Alembic commands ###
