"""epic_19

Revision ID: 3edb8f2c5bae
Revises: d3ddb4a2c466
Create Date: 2026-03-29 16:07:00.563160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3edb8f2c5bae'
down_revision: Union[str, Sequence[str], None] = 'd3ddb4a2c466'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('occupation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('automation_risk', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('remote_capable', sa.Boolean(), server_default='0', nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('occupation', schema=None) as batch_op:
        batch_op.drop_column('remote_capable')
        batch_op.drop_column('automation_risk')

    # ### end Alembic commands ###
