"""add telemetry models

Revision ID: 42c97cc78888
Revises: 671b532f6a03
Create Date: 2026-03-28 22:23:02.383345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42c97cc78888'
down_revision: Union[str, Sequence[str], None] = '671b532f6a03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page_view',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('query_params', sa.String(length=1000), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('page_view', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_page_view_timestamp'), ['timestamp'], unique=False)

    op.create_table('search_event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('query_text', sa.String(length=500), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('search_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_search_event_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_event_timestamp'))

    op.drop_table('search_event')
    with op.batch_alter_table('page_view', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_page_view_timestamp'))

    op.drop_table('page_view')
    # ### end Alembic commands ###
