"""Add Epic 11b ONET tables

Revision ID: 4752b9ad344f
Revises: e7ef1fb634fe
Create Date: 2026-03-29 11:57:56.530744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4752b9ad344f'
down_revision: Union[str, Sequence[str], None] = 'e7ef1fb634fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('occupation_alias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('soc', sa.String(length=20), nullable=False),
    sa.Column('alias_title', sa.String(), nullable=False),
    sa.Column('short_title', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['soc'], ['occupation.soc'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('occupation_alias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_occupation_alias_soc'), ['soc'], unique=False)

    op.create_table('occupation_education',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('soc', sa.String(length=20), nullable=False),
    sa.Column('ed_level_code', sa.Integer(), nullable=False),
    sa.Column('ed_level_label', sa.String(length=100), nullable=True),
    sa.Column('pct_workers', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['soc'], ['occupation.soc'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('occupation_education', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_occupation_education_soc'), ['soc'], unique=False)

    op.create_table('occupation_skill',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('soc', sa.String(length=20), nullable=False),
    sa.Column('element_name', sa.String(length=255), nullable=False),
    sa.Column('importance_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['soc'], ['occupation.soc'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('occupation_skill', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_occupation_skill_soc'), ['soc'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('occupation_skill', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_occupation_skill_soc'))

    op.drop_table('occupation_skill')
    with op.batch_alter_table('occupation_education', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_occupation_education_soc'))

    op.drop_table('occupation_education')
    with op.batch_alter_table('occupation_alias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_occupation_alias_soc'))

    op.drop_table('occupation_alias')
    # ### end Alembic commands ###
