"""Add OccupationWage and ONET fields

Revision ID: 66a88b965019
Revises: 42c97cc78888
Create Date: 2026-03-29 09:17:41.586238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66a88b965019'
down_revision: Union[str, Sequence[str], None] = '42c97cc78888'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('occupation_wage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('soc', sa.String(length=20), nullable=False),
    sa.Column('area_type', sa.String(length=50), nullable=False),
    sa.Column('area_code', sa.String(length=20), nullable=False),
    sa.Column('area_name', sa.String(length=255), nullable=True),
    sa.Column('employment_count', sa.Integer(), nullable=True),
    sa.Column('annual_mean_wage', sa.Float(), nullable=True),
    sa.Column('median_wage', sa.Float(), nullable=True),
    sa.Column('pct_25_wage', sa.Float(), nullable=True),
    sa.Column('pct_75_wage', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['soc'], ['occupation.soc'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('occupation_wage', schema=None) as batch_op:
        batch_op.create_index('ix_occupation_wage_area', ['area_type', 'area_code'], unique=False)
        batch_op.create_index('ix_occupation_wage_soc', ['soc'], unique=False)

    with op.batch_alter_table('occupation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_zone', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bright_outlook', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('occupation', schema=None) as batch_op:
        batch_op.drop_column('bright_outlook')
        batch_op.drop_column('job_zone')

    with op.batch_alter_table('occupation_wage', schema=None) as batch_op:
        batch_op.drop_index('ix_occupation_wage_soc')
        batch_op.drop_index('ix_occupation_wage_area')

    op.drop_table('occupation_wage')
    # ### end Alembic commands ###
