"""add org_fact table

Revision ID: 671b532f6a03
Revises: 22cd3f3f87eb
Create Date: 2026-03-28 21:45:58.387353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '671b532f6a03'
down_revision: Union[str, Sequence[str], None] = '22cd3f3f87eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org_fact',
    sa.Column('fact_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('fact_type', sa.String(length=50), nullable=False),
    sa.Column('value_num', sa.Float(), nullable=True),
    sa.Column('value_text', sa.String(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('as_of_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organization.org_id'], ),
    sa.PrimaryKeyConstraint('fact_id')
    )
    with op.batch_alter_table('org_fact', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_org_fact_org_id'), ['org_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('org_fact', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_org_fact_org_id'))

    op.drop_table('org_fact')
    # ### end Alembic commands ###
