"""Add naics_code to Organization

Revision ID: 68d886ee0528
Revises: 3edb8f2c5bae
Create Date: 2026-03-29 19:49:02.463188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68d886ee0528'
down_revision: Union[str, Sequence[str], None] = '3edb8f2c5bae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('naics_code', sa.String(length=6), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_column('naics_code')

    # ### end Alembic commands ###
