"""Initial schema

Revision ID: 6ca14d68c2f6
Revises: 
Create Date: 2026-03-26 11:30:51.362528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ca14d68c2f6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('civic_signal',
    sa.Column('signal_id', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('geoid', sa.String(length=20), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('signal_id')
    )
    op.create_table('dataset_source',
    sa.Column('source_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('loaded_at', sa.DateTime(), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('source_id')
    )
    op.create_table('geo_area',
    sa.Column('geoid', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('county_fips', sa.String(length=5), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('geoid')
    )
    op.create_table('occupation',
    sa.Column('soc', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('soc_major', sa.String(length=10), nullable=True),
    sa.Column('soc_minor', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('soc')
    )
    op.create_table('organization',
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('org_type', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('county_fips', sa.String(length=5), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('unitid', sa.String(length=50), nullable=True),
    sa.Column('ein', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('org_id')
    )
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.create_index('ix_organization_county_fips', ['county_fips'], unique=False)

    op.create_table('region',
    sa.Column('region_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('default_lat', sa.Float(), nullable=True),
    sa.Column('default_lon', sa.Float(), nullable=True),
    sa.Column('default_zoom', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('region_id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('relationship',
    sa.Column('rel_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_entity_type', sa.String(length=50), nullable=False),
    sa.Column('from_entity_id', sa.String(length=100), nullable=False),
    sa.Column('to_entity_type', sa.String(length=50), nullable=False),
    sa.Column('to_entity_id', sa.String(length=100), nullable=False),
    sa.Column('rel_type', sa.String(length=100), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_to', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('rel_id')
    )
    op.create_table('org_alias',
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organization.org_id'], ),
    sa.PrimaryKeyConstraint('org_id', 'source', 'source_id')
    )
    op.create_table('program',
    sa.Column('program_id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('credential_type', sa.String(length=100), nullable=False),
    sa.Column('cip', sa.String(length=10), nullable=False),
    sa.Column('modality', sa.String(length=50), nullable=True),
    sa.Column('completions', sa.Integer(), nullable=True),
    sa.Column('duration_weeks', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organization.org_id'], ),
    sa.PrimaryKeyConstraint('program_id')
    )
    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.create_index('ix_program_cip', ['cip'], unique=False)
        batch_op.create_index('ix_program_org_id', ['org_id'], unique=False)

    op.create_table('region_county',
    sa.Column('region_id', sa.String(length=50), nullable=False),
    sa.Column('county_fips', sa.String(length=5), nullable=False),
    sa.Column('county_name', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['region.region_id'], ),
    sa.PrimaryKeyConstraint('region_id', 'county_fips')
    )
    op.create_table('program_occupation',
    sa.Column('program_id', sa.String(length=36), nullable=False),
    sa.Column('soc', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['program.program_id'], ),
    sa.ForeignKeyConstraint(['soc'], ['occupation.soc'], ),
    sa.PrimaryKeyConstraint('program_id', 'soc')
    )
    with op.batch_alter_table('program_occupation', schema=None) as batch_op:
        batch_op.create_index('ix_program_occupation_program_id', ['program_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('program_occupation', schema=None) as batch_op:
        batch_op.drop_index('ix_program_occupation_program_id')

    op.drop_table('program_occupation')
    op.drop_table('region_county')
    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.drop_index('ix_program_org_id')
        batch_op.drop_index('ix_program_cip')

    op.drop_table('program')
    op.drop_table('org_alias')
    op.drop_table('relationship')
    op.drop_table('region')
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_index('ix_organization_county_fips')

    op.drop_table('organization')
    op.drop_table('occupation')
    op.drop_table('geo_area')
    op.drop_table('dataset_source')
    op.drop_table('civic_signal')
    # ### end Alembic commands ###
