"""Added OrgContact table

Revision ID: 77726879cce3
Revises: 8de14e753e21
Create Date: 2026-03-28 15:35:59.145226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77726879cce3'
down_revision: Union[str, Sequence[str], None] = '8de14e753e21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org_contact',
    sa.Column('contact_id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('contact_role', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organization.org_id'], ),
    sa.PrimaryKeyConstraint('contact_id')
    )
    with op.batch_alter_table('org_contact', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_org_contact_org_id'), ['org_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('org_contact', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_org_contact_org_id'))

    op.drop_table('org_contact')
    # ### end Alembic commands ###
