"""industry_flow_j2j

Revision ID: 81c81263b9f8
Revises: 68d886ee0528
Create Date: 2026-03-29 20:37:32.977619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81c81263b9f8'
down_revision: Union[str, Sequence[str], None] = '68d886ee0528'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('industry_flow_j2j',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('origin_naics', sa.String(length=6), nullable=False),
    sa.Column('destination_naics', sa.String(length=6), nullable=False),
    sa.Column('transitions', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('industry_flow_j2j', schema=None) as batch_op:
        batch_op.create_index('ix_industry_flow_dest', ['destination_naics'], unique=False)
        batch_op.create_index('ix_industry_flow_orig', ['origin_naics'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('industry_flow_j2j', schema=None) as batch_op:
        batch_op.drop_index('ix_industry_flow_orig')
        batch_op.drop_index('ix_industry_flow_dest')

    op.drop_table('industry_flow_j2j')
    # ### end Alembic commands ###
