"""Add apprenticeship partner flags to organization

Revision ID: 8de14e753e21
Revises: e40646ec9816
Create Date: 2026-03-28 14:55:47.660518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8de14e753e21'
down_revision: Union[str, Sequence[str], None] = 'e40646ec9816'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_apprenticeship_partner', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('apprenticeship_role', sa.String(length=50), nullable=True))

    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.alter_column('is_wioa_eligible',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('is_apprenticeship',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.alter_column('is_apprenticeship',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('is_wioa_eligible',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_column('apprenticeship_role')
        batch_op.drop_column('is_apprenticeship_partner')

    # ### end Alembic commands ###
