"""add occupation_projection

Revision ID: b3172ecdffcf
Revises: de0edbe1bb28
Create Date: 2026-03-29 12:41:43.358535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3172ecdffcf'
down_revision: Union[str, Sequence[str], None] = 'de0edbe1bb28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('occupation_projection',
    sa.Column('soc', sa.String(length=20), nullable=False),
    sa.Column('emp_2024', sa.Integer(), nullable=True),
    sa.Column('emp_2034', sa.Integer(), nullable=True),
    sa.Column('pct_change', sa.Float(), nullable=True),
    sa.Column('annual_openings', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['soc'], ['occupation.soc'], ),
    sa.PrimaryKeyConstraint('soc')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('occupation_projection')
    # ### end Alembic commands ###
