"""Add IndustryQCEW

Revision ID: d3ddb4a2c466
Revises: df939d840f5d
Create Date: 2026-03-29 14:26:29.499341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3ddb4a2c466'
down_revision: Union[str, Sequence[str], None] = 'df939d840f5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('industry_qcew',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('naics', sa.String(length=20), nullable=False),
    sa.Column('county_fips', sa.String(length=5), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=False),
    sa.Column('establishments', sa.Integer(), nullable=True),
    sa.Column('employment', sa.Integer(), nullable=True),
    sa.Column('avg_weekly_wage', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('industry_qcew', schema=None) as batch_op:
        batch_op.create_index('ix_industry_qcew_lookup', ['naics', 'county_fips'], unique=False)
        batch_op.create_index('ix_industry_qcew_time', ['year', 'quarter'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('industry_qcew', schema=None) as batch_op:
        batch_op.drop_index('ix_industry_qcew_time')
        batch_op.drop_index('ix_industry_qcew_lookup')

    op.drop_table('industry_qcew')
    # ### end Alembic commands ###
