"""add occupation_industry

Revision ID: df939d840f5d
Revises: b3172ecdffcf
Create Date: 2026-03-29 13:25:02.033220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df939d840f5d'
down_revision: Union[str, Sequence[str], None] = 'b3172ecdffcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('occupation_industry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('soc', sa.String(length=20), nullable=False),
    sa.Column('naics', sa.String(length=20), nullable=False),
    sa.Column('industry_title', sa.String(), nullable=False),
    sa.Column('employment_2024', sa.Integer(), nullable=True),
    sa.Column('pct_of_occupation', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['soc'], ['occupation.soc'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('occupation_industry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_occupation_industry_soc'), ['soc'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('occupation_industry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_occupation_industry_soc'))

    op.drop_table('occupation_industry')
    # ### end Alembic commands ###
