"""Add ONET occupation details

Revision ID: e7ef1fb634fe
Revises: 66a88b965019
Create Date: 2026-03-29 11:27:05.321215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7ef1fb634fe'
down_revision: Union[str, Sequence[str], None] = '66a88b965019'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('occupation_task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('soc', sa.String(length=20), nullable=False),
    sa.Column('task_statement', sa.String(), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['soc'], ['occupation.soc'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('occupation_task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_occupation_task_soc'), ['soc'], unique=False)

    op.create_table('occupation_tech_skill',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('soc', sa.String(length=20), nullable=False),
    sa.Column('example', sa.String(), nullable=False),
    sa.Column('hot_technology', sa.Boolean(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['soc'], ['occupation.soc'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('occupation_tech_skill', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_occupation_tech_skill_soc'), ['soc'], unique=False)

    op.create_table('related_occupation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('soc', sa.String(length=20), nullable=False),
    sa.Column('related_soc', sa.String(length=20), nullable=False),
    sa.Column('relatedness_tier', sa.String(length=50), nullable=True),
    sa.Column('index_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['related_soc'], ['occupation.soc'], ),
    sa.ForeignKeyConstraint(['soc'], ['occupation.soc'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('related_occupation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_related_occupation_related_soc'), ['related_soc'], unique=False)
        batch_op.create_index(batch_op.f('ix_related_occupation_soc'), ['soc'], unique=False)

    with op.batch_alter_table('occupation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('occupation', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('related_occupation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_related_occupation_soc'))
        batch_op.drop_index(batch_op.f('ix_related_occupation_related_soc'))

    op.drop_table('related_occupation')
    with op.batch_alter_table('occupation_tech_skill', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_occupation_tech_skill_soc'))

    op.drop_table('occupation_tech_skill')
    with op.batch_alter_table('occupation_task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_occupation_task_soc'))

    op.drop_table('occupation_task')
    # ### end Alembic commands ###
