"""Add org completions

Revision ID: efbc556a933c
Revises: 2a013d1fc882
Create Date: 2026-03-28 19:40:13.526190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efbc556a933c'
down_revision: Union[str, Sequence[str], None] = '2a013d1fc882'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_completions_demo',
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('total_completions', sa.Integer(), nullable=True),
    sa.Column('pct_men', sa.Float(), nullable=True),
    sa.Column('pct_women', sa.Float(), nullable=True),
    sa.Column('pct_white', sa.Float(), nullable=True),
    sa.Column('pct_black', sa.Float(), nullable=True),
    sa.Column('pct_hispanic', sa.Float(), nullable=True),
    sa.Column('pct_asian', sa.Float(), nullable=True),
    sa.Column('pct_native', sa.Float(), nullable=True),
    sa.Column('pct_pacific', sa.Float(), nullable=True),
    sa.Column('pct_two_or_more', sa.Float(), nullable=True),
    sa.Column('pct_unknown', sa.Float(), nullable=True),
    sa.Column('pct_non_resident', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organization.org_id'], ),
    sa.PrimaryKeyConstraint('org_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organization_completions_demo')
    # ### end Alembic commands ###
